### PR TITLE
Add Unclaimed Crop Block Files

### PR DESCRIPTION
**Pull request by smsunarto**
Missed this on the last PR.

### CODE REVIEW

**Comment by Cervator** [comment]
Cool, thanks :-) Is this related to GCI at all or just a freebie? Man it is going to be so much less confusing after GCI ends, hehe :D

**Comment by smsunarto** [comment]
@Cervator kinda, but not really. The textures file are GCI (from the previous PR) are related. But these files are not.

**Comment by smsunarto** [comment]
@Cervator it's not related to a task. Just adding this file to give some life to the assets that I made.

**Comment by Cervator** [comment]
Alright! Just wanted to make sure. Tests out good - merged :-) Thanks!

**Pull request merged**
