### PR TITLE
Adding flag prefab and code for activation

### PR DESCRIPTION
**Pull request by dacharya64**
Adding code that will go with PR L&S https://github.com/Terasology/LightAndShadow/pull/64 that allows the flag to be picked up on activation (pressing `E`). Also adds code letting it be auto picked up on breaking.

Also reduces hardness of flags to 1, making them easier to pick up after breaking

### CODE REVIEW

**Comment by nihal111** [comment]
This looks great, but I feel that we'll need a `BlackFlagComponent` and a `RedFlagComponent` later anyway, so might be a good idea to bundle it in with this PR (along with corresponding changes in https://github.com/Terasology/LightAndShadow/pull/64/).

**Comment by Cervator** [comment]
> I feel that we'll need a `BlackFlagComponent` and a `RedFlagComponent`

In that case would it be better with a `FlagComponent` with a faction variable in it?

**Comment by nihal111** [comment]
@Cervator Yep, that'll work and may be better :)

**Comment by dacharya64** [comment]
Instead of having a flagComponent, I was thinking of just having the flag prefab have a LASTeam component with a string that determines the team that they're on (as was set up before). Thoughts?

**Comment by nihal111** [comment]
@dacharya64 that's simply a different name for the suggested `flagComponent` unless you plan to use it outside the flag blocks too. Do you?

**Comment by dacharya64** [comment]
Yeah I did plan on it possibly being used on other items too, though this might not extend to what is implemented during GSoC. For instance chess items like RedKing, etc have a LASTeam component.

**Comment by nihal111** [comment]
@dacharya64  In that case the LASTeam component could be used to mark the faction. But it's very likely that you'd need to identify a flag specifically at some point. We should have a simple `FlagComponent` for that. This could be in addition to the `LASTeam` component.
Saves us from doing a prefab match and makes it easier to find a flag and who possesses it, should we need it at some point.

**Comment by dacharya64** [comment]
Makes sense. Just added it to here and https://github.com/Terasology/LightAndShadow/pull/64

**Pull request merged**
