### PR TITLE
fix: chess piece assets

### PR DESCRIPTION
**Pull request by jdrueckert**
- restructured chess piece assets into subdirectories for better overview
- added missing prefabs, materials for bishops
- added missing skeletalMesh for knights
- added missing texture for black bishop
- fixed height offsets for rooks, knights
- fixed animation references (most were still md5-style)
- scaled chess pieces to be 
  - slightly below player-size (king, queen, fool, knight)
  - child-sized (pawn)
  - elephant-sized (rook)

**Note:** Needs https://github.com/MovingBlocks/Terasology/pull/4247 for testing

### CODE REVIEW

**Review by skaldarnar — COMMENTED** [review]
I could spawn all prefabs, see screenshot below:

Terasology-201114122344-2560x1376

There are a few things that may need to be addressed either now in this PR or later in a follow. As the models don't appear in the game yet, this can probably be done in a different PR.

- [ ] it looks like all models have different orientations (I've spawned all of them with the same player orientation, yet they look in different directions)
- [ ] when spawned via `spawnPrefab` the entities don't show any behavior, neither on the platform nor in the battle arena
- [ ] there is some quirk with the knight models which are only visible if you are far enough away from it :thinking: see two screenshot below
	Terasology-201114120120-1426x873
	Terasology-201114120122-1426x873

I'm leaving this as comment for now. Please respond to the "open" issues, i.e., whether you'd like to fix them in this PR or later. I'm waiting with my approval :wink:

**Comment by jdrueckert** [comment]
> * it looks like all models have different orientations (I've spawned all of them with the same player orientation, yet they look in different directions)
> * when spawned via spawnPrefab the entities don't show any behavior, neither on the platform nor in the battle arena

those two I'll take a look at in a follow-up. making them move will help in fixing the orientations.

> there is some quirk with the knight models which are only visible if you are far enough away from it thinking see two screenshot below

please try again with my latest commit, for me at least it works :sweat_smile: 
image
image

**Comment by skaldarnar** [comment]
Still the same problem for me :confused: Seems to be connected to the player's camera, as toggling `ghost` on and off will make the model (dis-) appear... :horse:

**Comment by 4Denthusiast** [comment]
I tested out the issue with the knight too. I'm using an Nvidia graphics card. When I approach within about 3 blocks of the black knight, it becomes invisible. Also, if I stand just far enough away so that I can see it, I can get it to disappear and reappear just by rotating without moving.

**Comment by jdrueckert** [comment]
I wrote an issue for the situation: https://github.com/Terasology/LightAndShadow/issues/169
Generally I think this PR improves the situation (e.g. before, knights were not visible _at all_ as the model was missing).
@skaldarnar @4Denthusiast would you be okay with merging this albeit the invisibility weirdness?

**Review by skaldarnar — APPROVED** [review]

**Pull request merged**
