### PR TITLE
Add Dice Blocks Assets

### PR DESCRIPTION
**Pull request by smsunarto**
Added dice block assets for 3 different colors.

### CODE REVIEW

**Comment by oniatus** [comment]
Fits perfectly for #38.
Can you also create a block definition for each dice?
Maybe with the white one as base and then red and black based on the block (See the [Magic Plank](https://github.com/Terasology/LightAndShadowResources/blob/master/assets/blocks/MagicPlank.block) for an example of a block depending/extending another).
Texturing for the sides should be very similar 😄  to the [Dice Tutorial](https://github.com/Terasology/TutorialAssetSystem/wiki/Add-A-Dice).

We could also add a mesh based dice later on but that would be out of scope for this PR, IMHO :)

**Comment by smsunarto** [comment]
@rzats can you check this?

**Comment by Cervator** [comment]
Looks good to me, all three dice can be requested and placed in-game :-)

I see a prefab and a sound effect, but the prefab is empty. Meant to add something extra, like how in the tutorial you can "roll" the dice on `e`? Feel free to add that in here sometime as well

For now - merged! And thanks as always :-)

**Comment by smsunarto** [comment]
@Cervator that is currently empty since I haven't create the roll dice code. Will do asap.

**Pull request merged**
